package KieRule;
import com.drools.model.User;
import com.drools.model.Product;

import java.util.List;
import org.apache.commons.collections4.CollectionUtils;

global java.util.List userProductsList;

function int compareTwoLists (List firstList, List secondList) {
    return CollectionUtils.intersection(firstList, secondList).size();
}

rule "Forbidden products"

when
product : Product (composition.size() != 0)
user: User (forbiddenItems.size() != 0, compareTwoLists(product.composition, user.forbiddenItems) > 0)
then
product.setShowToUser(true);
end;
